'use client';

import { WebSource } from '@/lib/types';

export interface ResearchBrief {
  id: string;
  title: string;
  topic: string;
  depth: 'standard' | 'deep' | 'comprehensive';
  objectives: string[];
  synthesis: string;
  keyFindings: string[];
  counterArguments?: string[];
  sources: WebSource[];
  takeaways: string[];
  createdAt: string;
  updatedAt: string;
}

const RESEARCH_STORAGE_KEY = 'nyra_research_briefs';

let cachedUserId: string | null = null;

function getStorageKey(userId?: string | null): string {
  const uid = userId || cachedUserId;
  return uid ? `nyra_research_${uid}` : RESEARCH_STORAGE_KEY;
}

export function setResearchActiveUser(userId: string | null): void {
  cachedUserId = userId;
}

export function getResearchBriefs(userId?: string): ResearchBrief[] {
  if (typeof window === 'undefined') return [];
  try {
    const key = getStorageKey(userId);
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : [];
  } catch (e) {
    console.error('Failed to load research briefs:', e);
    return [];
  }
}

export function saveResearchBriefs(briefs: ResearchBrief[], userId?: string): void {
  if (typeof window === 'undefined') return;
  try {
    const key = getStorageKey(userId);
    localStorage.setItem(key, JSON.stringify(briefs));
    window.dispatchEvent(new CustomEvent('nyra_research_updated', { detail: briefs }));
  } catch (e) {
    console.error('Failed to save research briefs:', e);
  }
}

export function saveResearchBrief(brief: ResearchBrief, userId?: string): void {
  const all = getResearchBriefs(userId).filter((b) => b.id !== brief.id);
  saveResearchBriefs([brief, ...all], userId);
}

export function deleteResearchBrief(id: string, userId?: string): boolean {
  const all = getResearchBriefs(userId).filter((b) => b.id !== id);
  saveResearchBriefs(all, userId);
  return true;
}

export function exportBriefAsMarkdown(brief: ResearchBrief): string {
  const sourcesMd = brief.sources.map((s, i) => `${i + 1}. [${s.title}](${s.url})`).join('\n');
  const findingsMd = brief.keyFindings.map((f) => `- ${f}`).join('\n');
  const takeawaysMd = brief.takeaways.map((t) => `- ${t}`).join('\n');

  return `# ${brief.title}
*Research Brief generated by Nyra AI Workspace on ${new Date(brief.createdAt).toLocaleDateString()}*

## Topic & Focus
${brief.topic}

## Executive Summary & Deep Synthesis
${brief.synthesis}

## Key Discoveries & Findings
${findingsMd || 'No specific findings recorded.'}

## Key Takeaways & Recommendations
${takeawaysMd || 'None recorded.'}

## References & Sources
${sourcesMd || 'No direct web sources referenced.'}
`;
}
